
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#undef HKL_DISABLE_DEPRECATED
#define HKL_ENABLE_BROKEN
#include <glib-object.h>
#include "hkl.h"
#include "hkl-type-builtins.h"
/* enumerations from "../hkl.h" */
GType
hkl_unit_enum_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { HKL_UNIT_DEFAULT, "HKL_UNIT_DEFAULT", "default" },
            { HKL_UNIT_USER, "HKL_UNIT_USER", "user" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("HklUnitEnum"), values);
    }
    return etype;
}
GType
hkl_detector_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { HKL_DETECTOR_TYPE_0D, "HKL_DETECTOR_TYPE_0D", "0d" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("HklDetectorType"), values);
    }
    return etype;
}
GType
hkl_engine_capabilities_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { HKL_ENGINE_CAPABILITIES_READABLE, "HKL_ENGINE_CAPABILITIES_READABLE", "readable" },
            { HKL_ENGINE_CAPABILITIES_WRITABLE, "HKL_ENGINE_CAPABILITIES_WRITABLE", "writable" },
            { HKL_ENGINE_CAPABILITIES_INITIALIZABLE, "HKL_ENGINE_CAPABILITIES_INITIALIZABLE", "initializable" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("HklEngineCapabilities"), values);
    }
    return etype;
}
GType
hkl_engine_axis_names_get_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { HKL_ENGINE_AXIS_NAMES_GET_READ, "HKL_ENGINE_AXIS_NAMES_GET_READ", "read" },
            { HKL_ENGINE_AXIS_NAMES_GET_WRITE, "HKL_ENGINE_AXIS_NAMES_GET_WRITE", "write" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("HklEngineAxisNamesGet"), values);
    }
    return etype;
}
GType
hkl_engine_dependencies_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { HKL_ENGINE_DEPENDENCIES_AXES, "HKL_ENGINE_DEPENDENCIES_AXES", "axes" },
            { HKL_ENGINE_DEPENDENCIES_ENERGY, "HKL_ENGINE_DEPENDENCIES_ENERGY", "energy" },
            { HKL_ENGINE_DEPENDENCIES_SAMPLE, "HKL_ENGINE_DEPENDENCIES_SAMPLE", "sample" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("HklEngineDependencies"), values);
    }
    return etype;
}
#define __HKL_TYPE_BUILTINS_C__

/* Generated data ends here */

