
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __HKL_TYPE_BUILTINS_H__
#define __HKL_TYPE_BUILTINS_H__

#include <glib.h>               // for G_BEGIN_DECLS, G_END_DECLS, etc
#include <glib-object.h>	// GType
#include "hkl.h"                // for HKLAPI

G_BEGIN_DECLS

/* enumerations from "../hkl.h" */
HKLAPI GType hkl_unit_enum_get_type (void) G_GNUC_CONST;
#define HKL_TYPE_UNIT_ENUM (hkl_unit_enum_get_type ())
HKLAPI GType hkl_detector_type_get_type (void) G_GNUC_CONST;
#define HKL_TYPE_DETECTOR_TYPE (hkl_detector_type_get_type ())
HKLAPI GType hkl_engine_capabilities_get_type (void) G_GNUC_CONST;
#define HKL_TYPE_ENGINE_CAPABILITIES (hkl_engine_capabilities_get_type ())
HKLAPI GType hkl_engine_axis_names_get_get_type (void) G_GNUC_CONST;
#define HKL_TYPE_ENGINE_AXIS_NAMES_GET (hkl_engine_axis_names_get_get_type ())
HKLAPI GType hkl_engine_dependencies_get_type (void) G_GNUC_CONST;
#define HKL_TYPE_ENGINE_DEPENDENCIES (hkl_engine_dependencies_get_type ())
G_END_DECLS

#endif /* __HKL_TYPE_BUILTINS_H__ */

/* Generated data ends here */

